name: Forklift_Release_KinD
on:
  workflow_dispatch:
      name:
        description: 'Run forklift release version on KinD'
        
jobs:
  doit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out forkliftci repository
        uses: actions/checkout@v3

      - run: echo "ðŸ’¡ The repository has been cloned to the runner."

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - run: echo "ðŸ This job's status is ${{ job.status }}."

      - run: echo `pwd` >> $GITHUB_PATH

      - run: cluster/kind/install_kind.sh

      - name: Get kubectl
        run: curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"

      - run: chmod u+x kubectl

      - run: kubectl version

      - run: cluster/k8s-deploy-kubevirt.sh

      - run: cluster/k8s-deploy-forklift.sh

      - run: kubectl wait deployment -n konveyor-forklift forklift-controller --for condition=Available=True --timeout=180s

      - run: echo "CLUSTER=`kind get kubeconfig | grep server | cut -d ' ' -f6`" >> $GITHUB_ENV
      
      - run: echo "TOKEN=`kubectl get secrets -n kube-system -o jsonpath='{.items[0].data.token-id}' | base64 -d`.`kubectl get secrets -n kube-system -o jsonpath='{.items[0].data.token-secret}' | base64 -d`" >> $GITHUB_ENV 

      - name: Test call to Forklift
        run: |
          curl -k "$CLUSTER/apis/forklift.konveyor.io/v1beta1/namespaces/konveyor-forklift/providers" --header "Authorization: Bearer $TOKEN"
